# -*- coding: utf-8 -*-
"""Projeto 1 - Detetive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NUO7ClhwnM5w1ZQJzVtCOs_arevH7pVN

Esse projeto tem a finalidade de fixar os conhecimentos de Variáveis, Print, Input
e Condicionais, para isso crie um programa que faça 5 perguntas para uma
pessoa sobre um crime. As perguntas são:

• "Você telefonou para a vítima?"

• " Você esteve no local do crime?"

• " Você mora perto da vítima?"

• " Você devia para a vítima?"

• " Você já trabalhou com a vítima?"

O programa deve, no final, emitir uma classificação sobre a participação da
pessoa no crime.

Se a pessoa responder positivamente a:

• 2 questões ela deve ser classificada como "Suspeita",

• Entre 3 e 4 como "Cúmplice"

• 5 como "Assassino".

• Caso contrário, ele será classificado como "Inocente".
"""

sim = 'S'
nao = 'N'
saladamista = 0


print('Olá, pedimos um pouco do seu tempo para realizarmos nossa investigação.\n\nPedimos que você mantenha a calma e responda ás perguntas calmamente.\n\nUtilize "S" para SIM, e "N" para NÃO.\n\nPodemos começar?')
inicio = input().upper()

if inicio == sim:
  print('Ótimo, vamos começar!')
  print()
  pera = input('Você telefonou para a vítima?').upper()
  if pera == sim:
    saladamista =+ 1

  else:
    pass

  print()
  
  uva = input('Você esteve no local do crime?').upper()
  if uva == sim:
    saladamista += 1
  else:
    pass

  print()

  maca = input('Você mora perto da vítima?').upper()
  if maca == sim:
    saladamista += 1

  else:
    pass

  print()

  goiaba = input('Você devia para a vítima?').upper()
  if goiaba == sim:
    saladamista += 1

  else:
    pass
  
  print()

  morango = input('Você já trabalhou com a vítima?').upper()
  if morango == sim:
    saladamista += 1
 
  else:
    pass
  
  print('\n\n\n')    

  if saladamista == 2:
    print('Você é SUSPEITO. Compareça à delegacia.')

  elif saladamista == 3 or saladamista == 4:
    print('Você é CÚMPLICE. Estamos avaliando os documentos para o seu PROCESSO.')

  elif saladamista == 5:
    print('Você é o ASSASSINO. Esse programa serve como um radar para caçá-lo.\nNesse momento, viaturas estão se encaminhando e você será DETIDO.\nNÃO SE MOVA.')  

  else:
    print('Você é INOCENTE. Não se preocupe! Você está limpo!')
    

elif inicio == nao:
  print('Nesse caso, compareça até a delegacia mais próxima, para prestar\ndepoimento presencialmente. ')  

else: 
  print('Não conseguimos computar sua resposta. Tente novamente.')